# Generated by Django 6.1 on 2026-09-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teachers', '0002_alter_teacher_options_teacher_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher')], db_index=True, default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='teacher_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='teachers.teacher'),
        ),
    ]
