# Generated by Django 6.1 on 2026-08-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_background_image',
            field=models.ImageField(blank=True, help_text='Background image for the admin dashboard.', null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_background_image',
            field=models.ImageField(blank=True, help_text='Background image for the main website.', null=True, upload_to='backgrounds/'),
        ),
    ]
