# Generated by Django 6.1 on 2026-09-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['order', '-date', '-id']},
        ),
    ]
