# Generated by Django 6.1 on 2026-09-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_album_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_focus_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='album',
            name='cover_focus_y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='album',
            name='cover_ratio',
            field=models.CharField(choices=[('landscape', 'Landscape (16:9)'), ('square', 'Square (1:1)'), ('portrait', 'Portrait (4:5)'), ('original', 'Original (no crop)')], default='landscape', max_length=12),
        ),
    ]
