# Generated by Django 6.1 on 2026-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shree Jaya Buddha English Boarding School', max_length=200)),
                ('short_name', models.CharField(default='SJBEBS', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('logo_url', models.URLField(blank=True)),
                ('hero_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1600&auto=format&fit=crop')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('phone_primary', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('map_embed_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
            },
        ),
    ]
