# Generated by Django 6.1 on 2026-09-29 12:24

import home_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='Welcome to SJBEBS', help_text='Small line above the heading, e.g. "Welcome to SJBEBS".', max_length=200)),
                ('heading', models.TextField(default='Nurturing Bright Minds,\nBuilding Futures', help_text='Main heading. Use a new line to break it across two lines.')),
                ('heading_highlight', models.CharField(blank=True, default='Bright Minds', help_text='Words inside the heading that are shown in gold.', max_length=100)),
                ('intro', models.TextField(blank=True, default='Shree Jaya Buddha English Boarding School — a premier institution committed to academic excellence and holistic student development.')),
                ('primary_button_text', models.CharField(blank=True, default='Apply Now →', max_length=60)),
                ('primary_button_url', models.CharField(blank=True, default='/admissions', max_length=300)),
                ('secondary_button_text', models.CharField(blank=True, default='Discover Our School', max_length=60)),
                ('secondary_button_url', models.CharField(blank=True, default='/about', max_length=300)),
                ('stats', models.JSONField(blank=True, default=home_page.models.default_stats, help_text='List of {"value": "25+", "label": "Years of Excellence"} objects.')),
                ('show_stats', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Hero',
                'verbose_name_plural': 'Home Page Hero',
            },
        ),
    ]
