# Generated by Django 6.1 on 2026-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('general', 'General'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('admission', 'Admission'), ('result', 'Result'), ('other', 'Other')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_important', '-published_date'],
            },
        ),
    ]
