# Generated by Django 6.1 on 2026-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_seed_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
