# Generated by Django 6.1 on 2026-09-30 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_teachingslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='classteacher',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_class_teacher', True)), fields=('school_class',), name='uniq_class_teacher_per_class'),
        ),
    ]
