# Generated by Django 6.1 on 2026-09-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_classteacher_is_class_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.schoolclass'),
        ),
    ]
