# Generated by Django 6.1 on 2026-10-01 03:36

import django.db.models.deletion
from django.db import migrations, models


def text_subjects_into_rows(apps, schema_editor):
    """
    TeachingSlot.subject used to be free text. Turn each distinct name into a
    real Subject so the existing periods keep their subject instead of being
    wiped when the column becomes a foreign key.

    A Subject must belong to a Programme, so the programme of the class the
    period was for is used. Periods whose class has no programme are collected
    under a single holding programme, which the admin can rename or split later.
    """
    TeachingSlot = apps.get_model('academics', 'TeachingSlot')
    Subject = apps.get_model('academics', 'Subject')
    Programme = apps.get_model('academics', 'Programme')

    holding, _ = Programme.objects.get_or_create(
        name='Subjects (migrated)',
        defaults={'level': '', 'description': 'Created when the timetable moved '
                                             'from typed subject names to real subjects.'},
    )

    for slot in TeachingSlot.objects.all().iterator():
        name = (slot.subject or '').strip()
        if not name:
            name = 'Unnamed subject'
        programme = None
        if slot.school_class_id:
            programme = slot.school_class.programme
        subject, _ = Subject.objects.get_or_create(
            programme=programme or holding,
            name=name,
            defaults={'order': 0},
        )
        # Remember the new row so the foreign key can point at it.
        slot.subject_id = subject.id
        slot.save(update_fields=['subject_id'])


def text_subjects_back_to_text(apps, schema_editor):
    """Reverse back to free text, using the subject's own name."""
    TeachingSlot = apps.get_model('academics', 'TeachingSlot')
    for slot in TeachingSlot.objects.select_related('subject').all().iterator():
        slot.subject = slot.subject.name
        slot.save(update_fields=['subject'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_classteacher_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingslot',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.RenameField(
            model_name='teachingslot',
            old_name='subject',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='teachingslot',
            name='subject',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='timetable_slots',
                to='academics.subject',
            ),
        ),
        migrations.RunPython(text_subjects_into_rows, text_subjects_back_to_text),
        migrations.AlterField(
            model_name='teachingslot',
            name='subject',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='timetable_slots',
                to='academics.subject',
            ),
        ),
    ]
