# Generated by Django 6.1 on 2026-10-01 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_teachingslot_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingslot',
            name='subject_name',
        ),
    ]
