# Generated by Django 6.1 on 2026-10-02 08:48

import django.db.models.deletion
from django.db import migrations, models


def publish_existing_documents(apps, schema_editor):
    """
    Documents already on the site stay on the site.

    `status` arrives as Draft for every row, which is the right default for a
    document an admin is about to write but the wrong reading for the ones
    that were already being listed on the public Academics page. Marking them
    published keeps the public pages exactly as they were.
    """
    AcademicDocument = apps.get_model('academics', 'AcademicDocument')
    AcademicDocument.objects.all().update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_student_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('true_false', 'True / False')], default='short_answer', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_option', models.CharField(blank=True, max_length=1)),
                ('answer', models.TextField(blank=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='academicdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='academicdocument',
            name='client_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='academicdocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academicdocument',
            name='document_type',
            field=models.CharField(choices=[('study_material', 'Chapter / Study Material'), ('pdf_notes', 'PDF / Notes'), ('questions', 'Questions'), ('qa', 'Questions & Answers'), ('assignment', 'Assignment'), ('pyq', 'Previous Year Questions'), ('other', 'Other')], default='study_material', max_length=20),
        ),
        migrations.AddField(
            model_name='academicdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='academicdocument',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='academicdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicdocument',
            name='file_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academics.subject')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='academicdocument',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='academics.chapter'),
        ),
        migrations.AddConstraint(
            model_name='academicdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('client_token', ''), _negated=True), fields=('client_token',), name='uniq_document_client_token'),
        ),
        migrations.AddField(
            model_name='documentquestion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.academicdocument'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='uniq_chapter_per_subject'),
        ),
        migrations.RunPython(publish_existing_documents, migrations.RunPython.noop),
    ]
