# Generated by Django 6.1 on 2026-10-02 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_documentquestion_alter_academicdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teachingslot',
            name='uniq_teacher_slot_start',
        ),
        migrations.AddField(
            model_name='teachingslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='teachingslot',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', True)), fields=('teacher', 'school_class', 'day_of_week', 'start_time'), name='uniq_teacher_slot_start'),
        ),
        migrations.AddConstraint(
            model_name='teachingslot',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', False)), fields=('teacher', 'school_class', 'date', 'start_time'), name='uniq_teacher_dated_slot_start'),
        ),
    ]
