# Generated by Django 6.1 on 2026-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('type', models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='news', max_length=10)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=400)),
                ('cover_image_url', models.URLField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News / Event',
                'verbose_name_plural': 'News & Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
