# Generated by Django 6.1 on 2026-09-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='popup_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='show_popup',
            field=models.BooleanField(default=False),
        ),
    ]
