# Generated by Django 6.1 on 2026-09-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_events', '0002_newsevent_popup_expires_at_newsevent_show_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='cover_focus_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='cover_focus_y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='cover_ratio',
            field=models.CharField(choices=[('landscape', 'Landscape (16:9)'), ('square', 'Square (1:1)'), ('portrait', 'Portrait (4:5)'), ('original', 'Original (no crop)')], default='landscape', max_length=12),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='excerpt',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='title',
            field=models.CharField(max_length=1500),
        ),
    ]
